# Generated by Django 2.2.12 on 2020-06-06 03:32

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='fotos/static/images/no-img.jpg', upload_to='fotos')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='interno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('detalle', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, upload_to='docs', verbose_name='Documento')),
                ('remitente', models.CharField(blank=True, max_length=200, verbose_name='Remitente')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_recepcion', models.DateTimeField(null=True, verbose_name='Fecha de recepción')),
                ('receptor', models.CharField(blank=True, max_length=200, verbose_name='Receptor')),
                ('area', models.CharField(choices=[('DIRECTOR', 'Director'), ('COORDINADOR GENERAL', 'Coordinador general'), ('ENCARGADA DE PLATAFORMA', 'Encargada de plataforma'), ('FACILITADOR DE PROGRAMAS', 'Facilitador de programas'), ('ENCARGADA DE FINANZAS', 'Encargada de finanzas'), ('SECRETARIA', 'Secretaria')], default='CÍVIL', max_length=30, verbose_name='Area Interna')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=100, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Interno',
                'verbose_name_plural': 'Internos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='programas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('horas', models.CharField(blank=True, max_length=50, verbose_name='Horas')),
                ('creditos', models.CharField(blank=True, max_length=50, verbose_name='Creditos')),
                ('costo', models.FloatField(max_length=200, null=True, verbose_name='Costo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de culminación')),
                ('tipo', models.CharField(choices=[('DIPLOMADO', 'Diplomado'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('POSDOCTORADO', 'Posdoctorado'), ('CURSO DE EDUCACION CONTINUA', 'Curso de educacion continua')], default='DIPLOMADO', max_length=60, verbose_name='Tipo de programa académico')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='modulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('horas', models.CharField(blank=True, max_length=100, verbose_name='Horas')),
                ('id_programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.programas')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('ci', models.IntegerField(max_length=30, null=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Telefno')),
                ('correo', models.EmailField(blank=True, max_length=30, verbose_name='Correo')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('PREFIERO NO DECIRLO', 'Prefiero no decirlo')], default='MASCULINO', max_length=30, verbose_name='Sexo')),
                ('fuerza', models.CharField(choices=[('CÍVIL', 'civil'), ('EJÉCITO', 'Ejercito'), ('FUERZA AÉREA', 'Fuerza aérea'), ('ARMADA', 'Armada')], default='CÍVIL', max_length=30, verbose_name='Fuerza')),
                ('nacionalidad', models.CharField(blank=True, max_length=30, verbose_name='Nacionalidad')),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('APROBADO PARCIALMENTE', 'Aprobado parcialmente'), ('PARA REVISAR', 'Para revisar'), ('OBSERVADO', 'Observado')], default='PARA REVISAR', max_length=100, verbose_name='Estado')),
                ('estado_seleccion', models.CharField(choices=[('SELECCIONADO', 'Seleccionado'), ('DESCARTADO', 'Descartado'), ('PARA REVISAR', 'Para revisar')], default='PARA REVISAR', max_length=100, verbose_name='Estado selección')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('estado_imagen', models.BooleanField(default=False, verbose_name='Estado de Imagen')),
                ('curriculum', models.FileField(blank=True, upload_to='docs', verbose_name='Curriculum')),
                ('estado_curriculum', models.BooleanField(default=False, verbose_name='Estado de curriculum')),
                ('titulo', models.FileField(upload_to='docs', verbose_name='Titulo en provision nacional')),
                ('estado_titulo', models.BooleanField(default=False, verbose_name='Estado del titulo')),
                ('diplomado', models.FileField(upload_to='docs', verbose_name='Titulo de diplomado')),
                ('maestria', models.FileField(upload_to='docs', verbose_name='Titulo de maestria')),
                ('estado_maestria', models.BooleanField(default=False, verbose_name='Estado de maestria')),
                ('doctorado', models.FileField(blank=True, upload_to='docs', verbose_name='Titulo de doctorado')),
                ('posdoctorado', models.FileField(blank=True, upload_to='docs', verbose_name='Titulo de Posdoctorado')),
                ('actual', models.DateTimeField(default=datetime.datetime.now, verbose_name='Actual')),
                ('comentarios', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('codigoS', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('codigo_titulo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('codigo_diplomado', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('codigo_maestria', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id_modulos', models.ManyToManyField(to='docente.modulos')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cursante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('fecha_de_envio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de envio')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('ci', models.IntegerField(max_length=30, null=True, verbose_name='Cédula')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('PREFIERO NO DECIRLO', 'Prefiero no decirlo')], default='MASCULINO', max_length=30, verbose_name='Sexo')),
                ('fuerza', models.CharField(choices=[('CÍVIL', 'civil'), ('EJÉCITO', 'Ejercito'), ('FUERZA AÉREA', 'Fuerza aérea'), ('ARMADA', 'Armada')], default='CÍVIL', max_length=30, verbose_name='Fuerza')),
                ('correo', models.EmailField(blank=True, max_length=30, verbose_name='Correo')),
                ('nacionalidad', models.CharField(blank=True, max_length=30, verbose_name='Nacionalidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('formulario', models.FileField(blank=True, upload_to='docs', verbose_name='Formulario')),
                ('carnet', models.FileField(blank=True, upload_to='docs', verbose_name='Cedula')),
                ('comprobante', models.FileField(upload_to='docs', verbose_name='Baucher')),
                ('compromiso', models.FileField(blank=True, upload_to='docs', verbose_name='Compromiso')),
                ('certificado', models.FileField(blank=True, upload_to='docs', verbose_name='Certificado')),
                ('luzagua', models.FileField(blank=True, upload_to='docs', verbose_name='Factura de luz/agua')),
                ('croquis', models.FileField(blank=True, upload_to='docs', verbose_name='Croquis')),
                ('curriculum', models.FileField(blank=True, upload_to='docs', verbose_name='Curriculum')),
                ('titulo', models.FileField(blank=True, upload_to='docs', verbose_name='Titulo Nivel nacional')),
                ('maestria', models.FileField(blank=True, upload_to='docs', verbose_name='Titulo Maestria')),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('APROBADO PARCIALMENTE', 'Aprobado parcialmente'), ('PARA REVISAR', 'Para revisar'), ('OBSERVADO', 'Observado')], default='PARA REVISAR', max_length=100, verbose_name='Estado')),
                ('codigoS', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('historial', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bitacora', models.CharField(blank=True, max_length=150, verbose_name='Bitacora')),
                ('fecha_revision', models.DateTimeField(null=True, verbose_name='Fecha de revision')),
                ('documento_observado', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('id_programas', models.ManyToManyField(to='docente.programas')),
            ],
            options={
                'verbose_name': 'Cursante',
                'verbose_name_plural': 'CUrsantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Codigos')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('docente_id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos',
                'ordering': ['codigo'],
            },
        ),
    ]
