# Generated by Django 2.2.12 on 2020-06-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_cursante_diplomado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='diplomado',
            field=models.FileField(blank=True, null=True, upload_to='docs', verbose_name='Titulo de diplomado'),
        ),
    ]
