# Generated by Django 2.2.12 on 2020-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_auto_20200611_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursante',
            name='carnet',
        ),
        migrations.RemoveField(
            model_name='cursante',
            name='compromiso',
        ),
        migrations.RemoveField(
            model_name='cursante',
            name='diplomado',
        ),
        migrations.RemoveField(
            model_name='cursante',
            name='maestria',
        ),
        migrations.AddField(
            model_name='cursante',
            name='cedula',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Cedula o pasaporte'),
        ),
        migrations.AddField(
            model_name='cursante',
            name='certificado_no_adeudo',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Certificado de no adeudo'),
        ),
        migrations.AddField(
            model_name='cursante',
            name='contrato',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='cursante',
            name='solicitud',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='cursante',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='certificado',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Certificado de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='comprobante',
            field=models.FileField(upload_to='docs', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='formulario',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Formulario de admisión'),
        ),
    ]
