# Generated by Django 2.2.12 on 2020-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_auto_20200611_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='fuerza',
            field=models.CharField(choices=[('CÍVIL', 'civil'), ('EJÉRCITO', 'Ejercito'), ('FUERZA AÉREA', 'Fuerza aérea'), ('ARMADA', 'Armada')], default='CÍVIL', max_length=30, verbose_name='Fuerza'),
        ),
    ]
