# Generated by Django 2.2.12 on 2020-06-15 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0005_auto_20200611_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='fecha_envio',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de envio'),
        ),
    ]
