# Generated by Django 2.2.12 on 2020-06-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_cursante_fecha_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='estado_certificado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='PARA REVISAR', max_length=100, verbose_name='Estado'),
        ),
    ]
