# Generated by Django 2.2.12 on 2020-06-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_auto_20200615_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='fecha_aprobacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado_cedula',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de cedula'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado_comprobante',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de comprobante'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado_contrato',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de contrato'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado_formulario',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de formulario'),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado_no_adeudo',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de no adeudo'),
        ),
    ]
