# Generated by Django 2.2.12 on 2020-06-16 04:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0009_auto_20200615_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='bitacora',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bitacora'),
        ),
        migrations.AddField(
            model_name='docente',
            name='documento_observado',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalles de la observación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_aprobacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_revision',
            field=models.DateTimeField(null=True, verbose_name='Fecha de revision'),
        ),
    ]
