# Generated by Django 2.2.12 on 2020-06-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0010_auto_20200616_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='estado_imagen',
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_curriculum',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de titulo'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_maestria',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de titulo'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_titulo',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de titulo'),
        ),
    ]
