# Generated by Django 2.2.12 on 2020-06-21 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docente', '0011_auto_20200616_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='id_usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursante',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('APROBADO PARCIALMENTE', 'Aprobado parcialmente'), ('PARA REVISAR', 'Para revisar')], default='PARA REVISAR', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_curriculum',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de curriculo'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_maestria',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='OBSERVADO', max_length=100, verbose_name='Estado de maestría'),
        ),
    ]
