# Generated by Django 2.2.12 on 2020-06-21 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docente', '0012_auto_20200621_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursante',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='cursante',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
