# Generated by Django 2.2.12 on 2020-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0013_auto_20200621_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='otro',
            field=models.FileField(null=True, upload_to='docs', verbose_name='Otros documentos adicionales'),
        ),
    ]
