# Generated by Django 2.2.12 on 2020-06-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0015_docente_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('APROBADO PARCIALMENTE', 'Aprobado parcialmente'), ('APROBADO FINANZAS', 'Aprobado finanzas'), ('PARA REVISAR', 'Para revisar')], default='PARA REVISAR', max_length=100, verbose_name='Estado'),
        ),
        migrations.RemoveField(
            model_name='cursante',
            name='id_programas',
        ),
        migrations.AddField(
            model_name='cursante',
            name='id_programas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docente.programas'),
        ),
    ]
