# Generated by Django 2.2.12 on 2020-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0016_auto_20200626_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='bitacora_finanzas',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bitacora'),
        ),
        migrations.AddField(
            model_name='cursante',
            name='fecha_revision_finanzas',
            field=models.DateTimeField(null=True, verbose_name='Fecha de revision finanzas'),
        ),
    ]
