# Generated by Django 2.2.12 on 2020-06-26 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0017_auto_20200626_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='fecha_envio_baucher',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de envio'),
        ),
    ]
