# Generated by Django 2.2.12 on 2020-06-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200601_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='mensaje_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='mensaje_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Mensaje'),
        ),
    ]
