# Generated by Django 2.2.12 on 2020-06-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200601_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_tipo',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('COORDINADOR GENERAL', 'Coordinador general'), ('ENCARGADA DE PLATAFORMA', 'Encargada de plataforma'), ('FACILITADOR DE PROGRAMAS', 'Facilitador de programas'), ('ENCARGADA DE FINANZAS', 'Encargada de finanzas'), ('SECRETARIA', 'Secretaria')], default='CÍVIL', max_length=30, verbose_name='Tipo'),
        ),
    ]
