# Generated by Django 2.2.12 on 2020-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=250, unique=True, verbose_name='Correo'),
        ),
    ]
