# Generated by Django 2.2.12 on 2020-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_tipo',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('COORDINADOR GENERAL', 'Coordinador general'), ('ENCARGADA DE PLATAFORMA', 'Encargada de plataforma'), ('FACILITADOR DE PROGRAMAS', 'Facilitador de programas'), ('ENCARGADA DE FINANZAS', 'Encargada de finanzas'), ('SECRETARIA', 'Secretaria'), ('DOCENTE', 'Docente'), ('CURSANTE', 'Cursante')], default='CURSANTE', max_length=30, verbose_name='Tipo'),
        ),
    ]
